on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v2
      with:
        token: ${{ secrets.TOKEN }}
        template: './resources/TEMPLATE.md'
        includeForks: true
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions
        git config user.email github-actions@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi