on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: generate-readme
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        template: './resources/TEMPLATE.md'
        includeForks: true
    - name: update-readme
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name "Anadi Nema"
        git config user.email ${{ secrets.USER_EMAIL }}
        git add .
        git commit -m "Update README"
        git push
        fi
